### ISSUE TITLE
Solution includes ColorSeclector component which isn't mentioned in the lab. 

### ISSUE THREAD

**Issue by bolloland** [learn-co-curriculum/react-simple-state-lab#37] opened 2021-10-15 02:17 UTC
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## (Optional) Proposed Solution

Is it possible to show a solution for those learning this code for the first time, to adhere to just "state" and "props" and use code that follows the instructions given in the lab? Please?

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by ihollander** [comment] 2021-10-25 19:03
Duplicate of #36

**Closed as completed by ihollander** 2021-10-25 19:03 UTC
